const { PrismaClient } = require('@prisma/client')
const { hash } = require('bcryptjs')

const prisma = new PrismaClient()

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}

function rand(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

const celebrities = [
  // ── MUSIC ──────────────────────────────────────────────────────────────
  { name: 'Taylor Swift', category: 'Music', subcategory: 'Pop', nationality: 'American', birthYear: 1989, meetPrice: 250000, virtualPrice: 75000, signingPrice: 50000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 18420, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png/440px-191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png', bio: 'Global pop superstar with multiple Grammy Awards and record-breaking albums including Midnights and The Eras Tour.', tags: 'pop,country,singer-songwriter,grammy', instagram: '@taylorswift', twitter: '@taylorswift13' },
  { name: 'Beyoncé', category: 'Music', subcategory: 'R&B', nationality: 'American', birthYear: 1981, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 22100, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png/440px-Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png', bio: 'Iconic Grammy-winning artist, performer, and cultural icon. Queen Bey has redefined modern music and performance.', tags: 'r&b,pop,queen-bey,grammy', instagram: '@beyonce' },
  { name: 'Drake', category: 'Music', subcategory: 'Hip-Hop', nationality: 'Canadian', birthYear: 1986, meetPrice: 300000, virtualPrice: 100000, signingPrice: 75000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 15300, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Drake_July_2016.jpg/440px-Drake_July_2016.jpg', bio: 'Multi-platinum rapper and songwriter from Toronto. Known for chart-topping hits and his OVO Sound label.', tags: 'hip-hop,rap,ovo,toronto', twitter: '@Drake' },
  { name: 'Adele', category: 'Music', subcategory: 'Soul/Pop', nationality: 'British', birthYear: 1988, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 12800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Adele_2016.jpg/440px-Adele_2016.jpg', bio: 'British soul powerhouse with multiple Grammy and Oscar wins. Known for Hello, Rolling in the Deep, and Someone Like You.', tags: 'soul,pop,british,grammy,oscar' },
  { name: 'Ed Sheeran', category: 'Music', subcategory: 'Pop', nationality: 'British', birthYear: 1991, meetPrice: 200000, virtualPrice: 60000, signingPrice: 40000, fanCardPrice: 39.99, rating: 4.8, reviewCount: 11200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ed_Sheeran-6886_%28cropped%29.jpg/440px-Ed_Sheeran-6886_%28cropped%29.jpg', bio: 'British singer-songwriter behind Shape of You, Thinking Out Loud, and countless platinum albums.', tags: 'pop,acoustic,singer-songwriter,british' },
  { name: 'Billie Eilish', category: 'Music', subcategory: 'Alt Pop', nationality: 'American', birthYear: 2001, meetPrice: 175000, virtualPrice: 55000, signingPrice: 35000, fanCardPrice: 39.99, rating: 4.8, reviewCount: 14500, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Billie_Eilish_wearing_a_black_hoodie_%28cropped%29.jpg/440px-Billie_Eilish_wearing_a_black_hoodie_%28cropped%29.jpg', bio: 'Grammy-winning Gen-Z icon and Oscar winner for No Time to Die. Pioneered a new era of alternative pop.', tags: 'alt-pop,indie,grammy,gen-z' },
  { name: 'The Weeknd', category: 'Music', subcategory: 'R&B', nationality: 'Canadian', birthYear: 1990, meetPrice: 275000, virtualPrice: 85000, signingPrice: 55000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 13100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/The_Weeknd_in_2018.png/440px-The_Weeknd_in_2018.png', bio: 'R&B superstar Abel Tesfaye, known for Blinding Lights, Starboy, and his cinematic musical aesthetic.', tags: 'r&b,pop,toronto,grammy' },
  { name: 'Ariana Grande', category: 'Music', subcategory: 'Pop', nationality: 'American', birthYear: 1993, meetPrice: 225000, virtualPrice: 70000, signingPrice: 45000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 17600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Ariana_Grande_2018.png/440px-Ariana_Grande_2018.png', bio: 'Pop sensation with a 4-octave vocal range. Known for thank u next, 7 rings, and her iconic ponytail.', tags: 'pop,r&b,actress,grammy' },
  { name: 'Rihanna', category: 'Music', subcategory: 'R&B', nationality: 'Barbadian', birthYear: 1988, meetPrice: 450000, virtualPrice: 140000, signingPrice: 90000, fanCardPrice: 54.99, rating: 4.9, reviewCount: 19200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Rihanna_Fenty_2018.png/440px-Rihanna_Fenty_2018.png', bio: 'Music icon, entrepreneur, and founder of Fenty Beauty. Known for Umbrella, Diamonds, and redefining beauty standards.', tags: 'r&b,pop,fenty,entrepreneur' },
  { name: 'Bruno Mars', category: 'Music', subcategory: 'Pop/R&B', nationality: 'American', birthYear: 1985, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 4.8, reviewCount: 10900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Bruno_Mars_2016.jpg/440px-Bruno_Mars_2016.jpg', bio: 'Multi-Grammy winning artist and showman. Known for Uptown Funk, Just the Way You Are, and electrifying live performances.', tags: 'pop,r&b,funk,grammy' },
  { name: 'Lady Gaga', category: 'Music', subcategory: 'Pop', nationality: 'American', birthYear: 1986, meetPrice: 350000, virtualPrice: 110000, signingPrice: 70000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 16400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Lady_Gaga_2019_by_Glenn_Francis.jpg/440px-Lady_Gaga_2019_by_Glenn_Francis.jpg', bio: 'Grammy and Oscar-winning artist, actress, and fashion icon. Known for Bad Romance, Shallow, and A Star Is Born.', tags: 'pop,dance,oscar,grammy,actress' },
  { name: 'Eminem', category: 'Music', subcategory: 'Hip-Hop', nationality: 'American', birthYear: 1972, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 14200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Eminem_at_the_2011_Grammys_%28cropped%29.jpg/440px-Eminem_at_the_2011_Grammys_%28cropped%29.jpg', bio: 'The greatest rapper of all time. Multi-Grammy winner and cultural icon with albums like The Slim Shady LP and Kamikaze.', tags: 'hip-hop,rap,detroit,grammy' },
  { name: 'Dua Lipa', category: 'Music', subcategory: 'Pop', nationality: 'British-Albanian', birthYear: 1995, meetPrice: 150000, virtualPrice: 48000, signingPrice: 32000, fanCardPrice: 34.99, rating: 4.7, reviewCount: 9800, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Dua_Lipa_2018.png/440px-Dua_Lipa_2018.png', bio: 'British-Albanian pop star known for Levitating, Don\'t Start Now, and her Future Nostalgia era.', tags: 'pop,dance,british,grammy' },
  { name: 'Harry Styles', category: 'Music', subcategory: 'Pop', nationality: 'British', birthYear: 1994, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 4.8, reviewCount: 13500, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Harry_Styles_in_2022_%28cropped%29.jpg/440px-Harry_Styles_in_2022_%28cropped%29.jpg', bio: 'Former One Direction member turned solo superstar. Known for Watermelon Sugar, As It Was, and iconic fashion.', tags: 'pop,rock,british,one-direction' },
  { name: 'Selena Gomez', category: 'Music', subcategory: 'Pop', nationality: 'American', birthYear: 1992, meetPrice: 175000, virtualPrice: 55000, signingPrice: 37000, fanCardPrice: 39.99, rating: 4.7, reviewCount: 12100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Selena_Gomez_in_2015.png/440px-Selena_Gomez_in_2015.png', bio: 'Pop star, actress, and founder of Rare Beauty. Known for Lose You to Love Me and her authentic advocacy.', tags: 'pop,actress,rare-beauty,philanthropist' },
  { name: 'Justin Bieber', category: 'Music', subcategory: 'Pop', nationality: 'Canadian', birthYear: 1994, meetPrice: 225000, virtualPrice: 70000, signingPrice: 48000, fanCardPrice: 44.99, rating: 4.6, reviewCount: 15800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Justin_Bieber_in_2015.jpg/440px-Justin_Bieber_in_2015.jpg', bio: 'Global pop icon who rose to fame at 15. Known for Baby, Love Yourself, and Peaches.', tags: 'pop,canadian,grammy' },
  { name: 'Katy Perry', category: 'Music', subcategory: 'Pop', nationality: 'American', birthYear: 1984, meetPrice: 175000, virtualPrice: 55000, signingPrice: 37000, fanCardPrice: 34.99, rating: 4.6, reviewCount: 8900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Katy_Perry_2018.jpg/440px-Katy_Perry_2018.jpg', bio: 'Pop mega-star known for Roar, Firework, and Teenage Dream. One of the best-selling music artists of all time.', tags: 'pop,american-idol-judge,grammy' },
  { name: 'Post Malone', category: 'Music', subcategory: 'Hip-Hop', nationality: 'American', birthYear: 1995, meetPrice: 175000, virtualPrice: 55000, signingPrice: 37000, fanCardPrice: 34.99, rating: 4.7, reviewCount: 9200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Post_Malone_2019.jpg/440px-Post_Malone_2019.jpg', bio: 'Multi-platinum rapper known for Rockstar, Circles, and Sunflower. Pioneer of genre-blending hip-hop.', tags: 'hip-hop,pop,trap,grammy' },
  { name: 'Nicki Minaj', category: 'Music', subcategory: 'Hip-Hop', nationality: 'Trinidadian-American', birthYear: 1982, meetPrice: 175000, virtualPrice: 55000, signingPrice: 37000, fanCardPrice: 39.99, rating: 4.7, reviewCount: 11500, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Nicki_Minaj_2018.png/440px-Nicki_Minaj_2018.png', bio: 'Queen of Rap. Multi-platinum artist and first female solo rapper to have 100 Billboard Hot 100 entries.', tags: 'hip-hop,rap,queen-of-rap,grammy' },
  { name: 'Jay-Z', category: 'Music', subcategory: 'Hip-Hop', nationality: 'American', birthYear: 1969, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 13700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Jay-Z_at_Cannes.jpg/440px-Jay-Z_at_Cannes.jpg', bio: 'Hip-hop legend, business mogul, and co-founder of Tidal. Known for 99 Problems and The Blueprint series.', tags: 'hip-hop,rap,entrepreneur,grammy' },
  { name: 'Kanye West', category: 'Music', subcategory: 'Hip-Hop', nationality: 'American', birthYear: 1977, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.5, reviewCount: 12400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Kanye_West_at_the_2009_Tribeca_Film_Festival.jpg/440px-Kanye_West_at_the_2009_Tribeca_Film_Festival.jpg', bio: 'Grammy-winning rapper, producer, and fashion designer. Known for College Dropout, Graduation, and Yeezy.', tags: 'hip-hop,rap,producer,fashion,grammy' },
  { name: 'Lizzo', category: 'Music', subcategory: 'Pop/R&B', nationality: 'American', birthYear: 1988, meetPrice: 120000, virtualPrice: 38000, signingPrice: 25000, fanCardPrice: 29.99, rating: 4.8, reviewCount: 7600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Lizzo_2019.jpg/440px-Lizzo_2019.jpg', bio: 'Body-positive pop star and multi-instrumentalist known for Truth Hurts and About Damn Time.', tags: 'pop,r&b,flute,body-positive,grammy' },
  { name: 'Cardi B', category: 'Music', subcategory: 'Hip-Hop', nationality: 'American', birthYear: 1992, meetPrice: 150000, virtualPrice: 48000, signingPrice: 32000, fanCardPrice: 34.99, rating: 4.7, reviewCount: 10300, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Cardi_B_2018.png/440px-Cardi_B_2018.png', bio: 'Bronx-born rapper known for I Like It, WAP, and Bodak Yellow — the first solo female rap #1 in 19 years.', tags: 'hip-hop,rap,grammy,bronx' },
  { name: 'Doja Cat', category: 'Music', subcategory: 'Pop/R&B', nationality: 'American', birthYear: 1995, meetPrice: 120000, virtualPrice: 38000, signingPrice: 25000, fanCardPrice: 29.99, rating: 4.7, reviewCount: 8700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Doja_Cat_2021.jpg/440px-Doja_Cat_2021.jpg', bio: 'Genre-blending pop artist known for Say So, Kiss Me More, and her viral internet persona.', tags: 'pop,r&b,rap,grammy,viral' },
  { name: 'Bad Bunny', category: 'Music', subcategory: 'Latin/Reggaeton', nationality: 'Puerto Rican', birthYear: 1994, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 14800, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Bad_Bunny_2020.jpg/440px-Bad_Bunny_2020.jpg', bio: 'Latin music superstar and most-streamed artist globally. Known for Me Porto Bonito and his genre-defining El Último Tour del Mundo.', tags: 'latin,reggaeton,trap,spanish' },
  { name: 'J Balvin', category: 'Music', subcategory: 'Latin/Reggaeton', nationality: 'Colombian', birthYear: 1985, meetPrice: 175000, virtualPrice: 55000, signingPrice: 37000, fanCardPrice: 34.99, rating: 4.7, reviewCount: 8900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/J_Balvin_2018.jpg/440px-J_Balvin_2018.jpg', bio: 'Colombian reggaeton superstar known for Mi Gente, Ginza, and his colorful fashion collaborations.', tags: 'latin,reggaeton,colombian' },
  { name: 'Shakira', category: 'Music', subcategory: 'Latin/Pop', nationality: 'Colombian', birthYear: 1977, meetPrice: 250000, virtualPrice: 80000, signingPrice: 50000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 11600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Shakira_2018.jpg/440px-Shakira_2018.jpg', bio: 'Global Latin superstar known for Hips Don\'t Lie and Waka Waka. UNESCO goodwill ambassador and philanthropist.', tags: 'latin,pop,colombian,grammy' },
  { name: 'Sam Smith', category: 'Music', subcategory: 'Soul/Pop', nationality: 'British', birthYear: 1992, meetPrice: 120000, virtualPrice: 38000, signingPrice: 25000, fanCardPrice: 29.99, rating: 4.7, reviewCount: 7200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Sam_Smith_2015_%28cropped%29.jpg/440px-Sam_Smith_2015_%28cropped%29.jpg', bio: 'Grammy and Oscar-winning British artist known for Stay With Me, Writing\'s on the Wall, and Unholy.', tags: 'soul,pop,british,grammy,oscar' },
  { name: 'Olivia Rodrigo', category: 'Music', subcategory: 'Pop/Rock', nationality: 'American', birthYear: 2003, meetPrice: 150000, virtualPrice: 48000, signingPrice: 32000, fanCardPrice: 34.99, rating: 4.8, reviewCount: 10200, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Olivia_Rodrigo_2021_%28cropped%29.jpg/440px-Olivia_Rodrigo_2021_%28cropped%29.jpg', bio: 'Grammy-winning Gen-Z star known for drivers license, good 4 u, and her debut album SOUR.', tags: 'pop,rock,gen-z,grammy' },
  { name: 'SZA', category: 'Music', subcategory: 'R&B', nationality: 'American', birthYear: 1990, meetPrice: 120000, virtualPrice: 38000, signingPrice: 25000, fanCardPrice: 29.99, rating: 4.8, reviewCount: 8400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/SZA_2018.jpg/440px-SZA_2018.jpg', bio: 'R&B singer-songwriter known for Kill Bill, Good Days, and her critically acclaimed album SOS.', tags: 'r&b,soul,tde,grammy' },

  // ── FILM & TV ───────────────────────────────────────────────────────────
  { name: 'Dwayne Johnson', category: 'Film & TV', subcategory: 'Action', nationality: 'American', birthYear: 1972, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 19800, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Dwayne_Johnson_2014_%28cropped%29.jpg/440px-Dwayne_Johnson_2014_%28cropped%29.jpg', bio: 'The Rock — Hollywood\'s highest-paid actor, former WWE champion, and global superstar known for Fast & Furious and Jumanji.', tags: 'action,wrestler,hollywood,fast-furious' },
  { name: 'Tom Hanks', category: 'Film & TV', subcategory: 'Drama', nationality: 'American', birthYear: 1956, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 54.99, rating: 5.0, reviewCount: 16700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Tom_Hanks_TIFF_2019.jpg/440px-Tom_Hanks_TIFF_2019.jpg', bio: 'America\'s Dad. Two-time Oscar winner known for Forrest Gump, Cast Away, Philadelphia, and Saving Private Ryan.', tags: 'drama,oscar,hollywood-legend' },
  { name: 'Leonardo DiCaprio', category: 'Film & TV', subcategory: 'Drama', nationality: 'American', birthYear: 1974, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 18300, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Leonardo_Dicaprio_Cannes_2019.jpg/440px-Leonardo_Dicaprio_Cannes_2019.jpg', bio: 'Oscar-winning actor known for Titanic, The Wolf of Wall Street, and The Revenant. Also a major environmental activist.', tags: 'drama,oscar,titanic,environmental' },
  { name: 'Margot Robbie', category: 'Film & TV', subcategory: 'Drama', nationality: 'Australian', birthYear: 1990, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 13600, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Margot_Robbie_2023.jpg/440px-Margot_Robbie_2023.jpg', bio: 'Oscar-nominated actress and producer known for Barbie, I, Tonya, and The Wolf of Wall Street.', tags: 'drama,comedy,producer,australian' },
  { name: 'Ryan Reynolds', category: 'Film & TV', subcategory: 'Comedy/Action', nationality: 'Canadian', birthYear: 1976, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 16100, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Ryan_Reynolds_2016.jpg/440px-Ryan_Reynolds_2016.jpg', bio: 'Deadpool star, Aviation Gin owner, and Wrexham AFC co-owner. Known for his witty humor and blockbuster roles.', tags: 'comedy,action,deadpool,entrepreneur' },
  { name: 'Scarlett Johansson', category: 'Film & TV', subcategory: 'Action/Drama', nationality: 'American', birthYear: 1984, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 49.99, rating: 4.8, reviewCount: 15400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Scarlett_Johansson_2010.jpg/440px-Scarlett_Johansson_2010.jpg', bio: 'Hollywood A-lister and Black Widow star. Known for her role in the Avengers series and Marriage Story.', tags: 'action,drama,marvel,black-widow' },
  { name: 'Robert Downey Jr.', category: 'Film & TV', subcategory: 'Action/Drama', nationality: 'American', birthYear: 1965, meetPrice: 600000, virtualPrice: 180000, signingPrice: 120000, fanCardPrice: 69.99, rating: 4.9, reviewCount: 21500, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg/440px-Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg', bio: 'Iron Man himself. Oscar-winning actor and one of Hollywood\'s most beloved stars of the Marvel Cinematic Universe.', tags: 'action,marvel,iron-man,oscar' },
  { name: 'Jennifer Lawrence', category: 'Film & TV', subcategory: 'Drama', nationality: 'American', birthYear: 1990, meetPrice: 275000, virtualPrice: 88000, signingPrice: 57000, fanCardPrice: 44.99, rating: 4.7, reviewCount: 12200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/JenniferLawrence_2013_%28cropped%29.jpg/440px-JenniferLawrence_2013_%28cropped%29.jpg', bio: 'Oscar-winning actress known for Silver Linings Playbook and The Hunger Games franchise.', tags: 'drama,oscar,hunger-games' },
  { name: 'Zendaya', category: 'Film & TV', subcategory: 'Drama', nationality: 'American', birthYear: 1996, meetPrice: 225000, virtualPrice: 70000, signingPrice: 47000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 14900, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Zendaya_2019.jpg/440px-Zendaya_2019.jpg', bio: 'Emmy-winning actress known for Euphoria and the Spider-Man franchise. Fashion icon and cultural trailblazer.', tags: 'drama,emmy,spiderman,euphoria,fashion' },
  { name: 'Chris Evans', category: 'Film & TV', subcategory: 'Action', nationality: 'American', birthYear: 1981, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 17800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Chris_Evans_2019.jpg/440px-Chris_Evans_2019.jpg', bio: 'Captain America himself. Known for the Avengers franchise and his advocacy work off-screen.', tags: 'action,marvel,captain-america,avengers' },
  { name: 'Jennifer Aniston', category: 'Film & TV', subcategory: 'Comedy/Drama', nationality: 'American', birthYear: 1969, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.8, reviewCount: 14600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Jennifer_Aniston_2019.jpg/440px-Jennifer_Aniston_2019.jpg', bio: 'Beloved Rachel Green from Friends. Emmy and Golden Globe winner with a massive film and TV career.', tags: 'comedy,drama,friends,emmy,golden-globe' },
  { name: 'Will Smith', category: 'Film & TV', subcategory: 'Action/Drama', nationality: 'American', birthYear: 1968, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.7, reviewCount: 13400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Will_Smith_2011.jpg/440px-Will_Smith_2011.jpg', bio: 'Oscar-winning actor known for Ali, King Richard, and blockbusters like Men in Black and Hitch.', tags: 'action,drama,comedy,oscar,rapper' },
  { name: 'Meryl Streep', category: 'Film & TV', subcategory: 'Drama', nationality: 'American', birthYear: 1949, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 5.0, reviewCount: 10800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Meryl_Streep_2012.jpg/440px-Meryl_Streep_2012.jpg', bio: 'The greatest living actress. Three-time Oscar winner known for Sophie\'s Choice, The Iron Lady, and Kramer vs. Kramer.', tags: 'drama,oscar-legend,hollywood' },
  { name: 'Brad Pitt', category: 'Film & TV', subcategory: 'Drama/Action', nationality: 'American', birthYear: 1963, meetPrice: 450000, virtualPrice: 135000, signingPrice: 90000, fanCardPrice: 54.99, rating: 4.9, reviewCount: 15900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Brad_Pitt_2019_by_Glenn_Francis.jpg/440px-Brad_Pitt_2019_by_Glenn_Francis.jpg', bio: 'Oscar-winning actor and producer known for Fight Club, Se7en, Once Upon a Time in Hollywood, and Troy.', tags: 'drama,action,oscar,producer' },
  { name: 'Angelina Jolie', category: 'Film & TV', subcategory: 'Action/Drama', nationality: 'American', birthYear: 1975, meetPrice: 450000, virtualPrice: 135000, signingPrice: 90000, fanCardPrice: 54.99, rating: 4.8, reviewCount: 14100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Angelina_Jolie_2019.jpg/440px-Angelina_Jolie_2019.jpg', bio: 'Oscar-winning actress, director, and UN refugee ambassador. Known for Lara Croft, Maleficent, and humanitarian work.', tags: 'action,drama,oscar,un-ambassador,director' },
  { name: 'Keanu Reeves', category: 'Film & TV', subcategory: 'Action', nationality: 'Canadian', birthYear: 1964, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 18700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Keanu_Reeves_2014.jpg/440px-Keanu_Reeves_2014.jpg', bio: 'Internet\'s nicest person and John Wick star. Known for The Matrix, Speed, and his legendary kindness.', tags: 'action,matrix,john-wick,internet-icon' },
  { name: 'Denzel Washington', category: 'Film & TV', subcategory: 'Drama', nationality: 'American', birthYear: 1954, meetPrice: 450000, virtualPrice: 135000, signingPrice: 90000, fanCardPrice: 54.99, rating: 5.0, reviewCount: 11300, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Denzel_Washington.jpg/440px-Denzel_Washington.jpg', bio: 'Two-time Oscar winner widely regarded as one of the greatest actors of his generation. Known for Training Day and Malcolm X.', tags: 'drama,oscar,training-day,malcolm-x' },
  { name: 'Chadwick Boseman', category: 'Film & TV', subcategory: 'Action/Drama', nationality: 'American', birthYear: 1976, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 54.99, rating: 5.0, reviewCount: 20400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Chadwick_Boseman_-_Black_Panther_premiere_in_Hollywood.jpg/440px-Chadwick_Boseman_-_Black_Panther_premiere_in_Hollywood.jpg', bio: 'The legendary Black Panther. Celebrated actor who portrayed iconic real-life figures and inspired millions worldwide.', tags: 'action,drama,marvel,black-panther,icon' },
  { name: 'Gal Gadot', category: 'Film & TV', subcategory: 'Action', nationality: 'Israeli', birthYear: 1985, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 13200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Gal_Gadot_2018.jpg/440px-Gal_Gadot_2018.jpg', bio: 'Wonder Woman herself. Israeli actress, model, and former Miss Israel known for the DC Extended Universe.', tags: 'action,wonder-woman,dc,miss-israel' },
  { name: 'Timothée Chalamet', category: 'Film & TV', subcategory: 'Drama', nationality: 'American-French', birthYear: 1995, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 4.8, reviewCount: 11800, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Timoth%C3%A9e_Chalamet_2018_%28cropped%29.jpg/440px-Timoth%C3%A9e_Chalamet_2018_%28cropped%29.jpg', bio: 'Oscar-nominated actor known for Call Me by Your Name, Dune, and Little Women. Hollywood\'s new golden boy.', tags: 'drama,oscar,dune,call-me-by-your-name' },
  { name: 'Florence Pugh', category: 'Film & TV', subcategory: 'Drama', nationality: 'British', birthYear: 1996, meetPrice: 175000, virtualPrice: 55000, signingPrice: 37000, fanCardPrice: 34.99, rating: 4.8, reviewCount: 9700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Florence_Pugh_2019.jpg/440px-Florence_Pugh_2019.jpg', bio: 'Oscar-nominated British actress known for Little Women, Midsommar, and Black Widow.', tags: 'drama,british,oscar,marvel' },
  { name: 'Pedro Pascal', category: 'Film & TV', subcategory: 'Action/Drama', nationality: 'Chilean-American', birthYear: 1975, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 4.9, reviewCount: 14300, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pedro_Pascal_%2848487290492%29_%28cropped%29.jpg/440px-Pedro_Pascal_%2848487290492%29_%28cropped%29.jpg', bio: 'The Mandalorian and Joel from The Last of Us. Chilean-American actor beloved as Daddy of the internet.', tags: 'action,drama,mandalorian,last-of-us' },

  // ── SPORTS ─────────────────────────────────────────────────────────────
  { name: 'LeBron James', category: 'Sports', subcategory: 'Basketball', nationality: 'American', birthYear: 1984, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 22700, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/LeBron_James_crop.jpg/440px-LeBron_James_crop.jpg', bio: 'King James — 4x NBA Champion, multiple MVP awards, and unanimous GOAT candidate. Also a film star and entrepreneur.', tags: 'basketball,nba,lakers,goat,entrepreneur' },
  { name: 'Cristiano Ronaldo', category: 'Sports', subcategory: 'Soccer', nationality: 'Portuguese', birthYear: 1985, meetPrice: 600000, virtualPrice: 180000, signingPrice: 120000, fanCardPrice: 69.99, rating: 4.9, reviewCount: 24500, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/440px-Cristiano_Ronaldo_2018.jpg', bio: 'CR7 — five-time Ballon d\'Or winner and one of the greatest footballers in history. Records abound.', tags: 'soccer,football,cr7,portugal,goat' },
  { name: 'Lionel Messi', category: 'Sports', subcategory: 'Soccer', nationality: 'Argentine', birthYear: 1987, meetPrice: 600000, virtualPrice: 180000, signingPrice: 120000, fanCardPrice: 69.99, rating: 5.0, reviewCount: 25100, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg/440px-Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg', bio: 'The GOAT. Eight-time Ballon d\'Or winner and 2022 World Cup champion. Greatest footballer of all time.', tags: 'soccer,football,argentina,world-cup,goat,ballon-dor' },
  { name: 'Serena Williams', category: 'Sports', subcategory: 'Tennis', nationality: 'American', birthYear: 1981, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 54.99, rating: 4.9, reviewCount: 17600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Serena_Williams_at_2013_US_Open.jpg/440px-Serena_Williams_at_2013_US_Open.jpg', bio: '23 Grand Slam titles. Serena Williams redefined tennis and became the greatest female athlete of all time.', tags: 'tennis,grand-slam,goat,entrepreneur' },
  { name: 'Roger Federer', category: 'Sports', subcategory: 'Tennis', nationality: 'Swiss', birthYear: 1981, meetPrice: 450000, virtualPrice: 135000, signingPrice: 90000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 16900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Roger_Federer_-_Wimbledon_2009_2.jpg/440px-Roger_Federer_-_Wimbledon_2009_2.jpg', bio: '20 Grand Slam titles and universally loved. The Swiss maestro who brought elegance and perfection to tennis.', tags: 'tennis,grand-slam,swiss,wimbledon' },
  { name: 'Tiger Woods', category: 'Sports', subcategory: 'Golf', nationality: 'American', birthYear: 1975, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.8, reviewCount: 14200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Tiger_Woods_2019_%28cropped%29.jpg/440px-Tiger_Woods_2019_%28cropped%29.jpg', bio: '15 Major championships and responsible for popularizing golf worldwide. One of sport\'s greatest comeback stories.', tags: 'golf,major,comeback,pga' },
  { name: 'Usain Bolt', category: 'Sports', subcategory: 'Athletics', nationality: 'Jamaican', birthYear: 1986, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 12800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Usain_Bolt_2012_Olympics_2.jpg/440px-Usain_Bolt_2012_Olympics_2.jpg', bio: 'The fastest man alive. 8 Olympic gold medals and multiple world records in 100m and 200m sprints.', tags: 'athletics,sprint,olympics,world-record,jamaican' },
  { name: 'Naomi Osaka', category: 'Sports', subcategory: 'Tennis', nationality: 'Japanese-American', birthYear: 1997, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 4.8, reviewCount: 9600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Naomi_Osaka_2020_US_Open.jpg/440px-Naomi_Osaka_2020_US_Open.jpg', bio: 'Four-time Grand Slam champion and mental health advocate. Pioneer for athlete wellness in professional sports.', tags: 'tennis,grand-slam,mental-health,japanese' },
  { name: 'Simone Biles', category: 'Sports', subcategory: 'Gymnastics', nationality: 'American', birthYear: 1997, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 13900, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Simone_Biles_2016.jpg/440px-Simone_Biles_2016.jpg', bio: 'The greatest gymnast of all time with 37 Olympic and World Championship medals. Symbol of courage and mental health.', tags: 'gymnastics,olympics,goat,mental-health' },
  { name: 'Stephen Curry', category: 'Sports', subcategory: 'Basketball', nationality: 'American', birthYear: 1988, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.9, reviewCount: 16100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Stephen_Curry_2019-20_%28cropped%29.jpg/440px-Stephen_Curry_2019-20_%28cropped%29.jpg', bio: 'Chef Curry — 4x NBA Champion and the greatest shooter in basketball history. Changed the game with the 3-pointer.', tags: 'basketball,nba,warriors,shooting,champion' },
  { name: 'Neymar Jr.', category: 'Sports', subcategory: 'Soccer', nationality: 'Brazilian', birthYear: 1992, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.7, reviewCount: 14700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Barcellona_vs_Paris_Saint-Germain%2C_Champions_League%2C_2017_%28Ney%29.jpg/440px-Barcellona_vs_Paris_Saint-Germain%2C_Champions_League%2C_2017_%28Ney%29.jpg', bio: 'Brazilian football wizard known for his flair, skill, and time at Barcelona, PSG, and the Seleção.', tags: 'soccer,football,brazil,barcelona,psg' },
  { name: 'Mike Tyson', category: 'Sports', subcategory: 'Boxing', nationality: 'American', birthYear: 1966, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 12400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Mike_Tyson_2019_by_Glenn_Francis.jpg/440px-Mike_Tyson_2019_by_Glenn_Francis.jpg', bio: 'Iron Mike — youngest heavyweight champion in history and one of boxing\'s most fearsome competitors of all time.', tags: 'boxing,heavyweight,champion,legend' },
  { name: 'Conor McGregor', category: 'Sports', subcategory: 'MMA', nationality: 'Irish', birthYear: 1988, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.7, reviewCount: 13100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Conor_McGregor_2015.jpg/440px-Conor_McGregor_2015.jpg', bio: 'The Notorious — dual UFC champion in featherweight and lightweight. First Irish UFC world champion and global MMA icon.', tags: 'mma,ufc,boxing,irish,champion' },
  { name: 'Kevin Durant', category: 'Sports', subcategory: 'Basketball', nationality: 'American', birthYear: 1988, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 13800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Kevin_Durant_%2848201605327%29_%28cropped%29.jpg/440px-Kevin_Durant_%2848201605327%29_%28cropped%29.jpg', bio: '2x NBA Champion and scoring machine. One of the most skilled forwards in basketball history.', tags: 'basketball,nba,nets,suns,champion' },
  { name: 'Rafael Nadal', category: 'Sports', subcategory: 'Tennis', nationality: 'Spanish', birthYear: 1986, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 54.99, rating: 4.9, reviewCount: 14500, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Rafael_Nadal_2015_Roland_Garros.jpg/440px-Rafael_Nadal_2015_Roland_Garros.jpg', bio: '22 Grand Slam champion and King of Clay. The ultimate warrior of tennis and Spanish sporting legend.', tags: 'tennis,grand-slam,spanish,clay,roland-garros' },

  // ── SOCIAL MEDIA & INFLUENCERS ─────────────────────────────────────────
  { name: 'MrBeast', category: 'Social Media', subcategory: 'YouTube', nationality: 'American', birthYear: 1998, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 4.9, reviewCount: 18900, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/MrBeast_November_2022.jpg/440px-MrBeast_November_2022.jpg', bio: 'World\'s most subscribed YouTuber known for insane challenges and philanthropic stunts. Founded MrBeast Burger and Feastables.', tags: 'youtube,philanthropy,challenges,entrepreneur' },
  { name: 'Emma Chamberlain', category: 'Social Media', subcategory: 'YouTube', nationality: 'American', birthYear: 2001, meetPrice: 80000, virtualPrice: 26000, signingPrice: 17000, fanCardPrice: 24.99, rating: 4.7, reviewCount: 8200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Emma_Chamberlain_2019_%28cropped%29.jpg/440px-Emma_Chamberlain_2019_%28cropped%29.jpg', bio: 'Gen-Z lifestyle and fashion YouTuber with millions of followers. Brand ambassador for Louis Vuitton and Chamberlaincoffee founder.', tags: 'youtube,fashion,coffee,lifestyle' },
  { name: 'Khaby Lame', category: 'Social Media', subcategory: 'TikTok', nationality: 'Italian-Senegalese', birthYear: 2000, meetPrice: 120000, virtualPrice: 38000, signingPrice: 25000, fanCardPrice: 29.99, rating: 4.8, reviewCount: 11600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Khaby_Lame_at_Cannes_2022.jpg/440px-Khaby_Lame_at_Cannes_2022.jpg', bio: 'Most followed TikToker globally. Known for his wordless reaction videos making fun of overly complicated life hacks.', tags: 'tiktok,viral,comedy,reaction' },
  { name: 'Addison Rae', category: 'Social Media', subcategory: 'TikTok', nationality: 'American', birthYear: 2000, meetPrice: 80000, virtualPrice: 26000, signingPrice: 17000, fanCardPrice: 24.99, rating: 4.6, reviewCount: 7400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Addison_Rae_2021.jpg/440px-Addison_Rae_2021.jpg', bio: 'TikTok superstar turned actress and singer. One of the highest-earning TikTok creators with 88M+ followers.', tags: 'tiktok,dance,actress,singer' },
  { name: 'Charli D\'Amelio', category: 'Social Media', subcategory: 'TikTok', nationality: 'American', birthYear: 2004, meetPrice: 100000, virtualPrice: 32000, signingPrice: 21000, fanCardPrice: 29.99, rating: 4.7, reviewCount: 9100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Charli_D%27Amelio_2021.jpg/440px-Charli_D%27Amelio_2021.jpg', bio: 'America\'s sweetheart of TikTok. Most followed TikTok creator in the US with 150M+ followers.', tags: 'tiktok,dance,gen-z' },

  // ── BUSINESS & TECH ─────────────────────────────────────────────────────
  { name: 'Elon Musk', category: 'Business & Tech', subcategory: 'Entrepreneur', nationality: 'South African-American', birthYear: 1971, meetPrice: 1000000, virtualPrice: 300000, signingPrice: 200000, fanCardPrice: 99.99, rating: 4.3, reviewCount: 21000, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg/440px-Elon_Musk_Royal_Society_%28crop2%29.jpg', bio: 'CEO of Tesla, SpaceX, and X (Twitter). World\'s richest person and visionary behind electric vehicles and space travel.', tags: 'entrepreneur,tesla,spacex,x,billionaire' },
  { name: 'Oprah Winfrey', category: 'Business & Tech', subcategory: 'Media', nationality: 'American', birthYear: 1954, meetPrice: 750000, virtualPrice: 225000, signingPrice: 150000, fanCardPrice: 79.99, rating: 5.0, reviewCount: 17300, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Oprah_in_2014.jpg/440px-Oprah_in_2014.jpg', bio: 'Media mogul, billionaire, and cultural icon. The Oprah Winfrey Show ran 25 seasons and changed daytime TV forever.', tags: 'media,entrepreneur,philanthropist,book-club,oscar' },
  { name: 'Mark Zuckerberg', category: 'Business & Tech', subcategory: 'Tech', nationality: 'American', birthYear: 1984, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.1, reviewCount: 12400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg/440px-Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg', bio: 'CEO and co-founder of Meta (Facebook, Instagram, WhatsApp). One of the world\'s youngest billionaires.', tags: 'tech,facebook,meta,instagram,billionaire' },
  { name: 'Jeff Bezos', category: 'Business & Tech', subcategory: 'Entrepreneur', nationality: 'American', birthYear: 1964, meetPrice: 750000, virtualPrice: 225000, signingPrice: 150000, fanCardPrice: 79.99, rating: 4.4, reviewCount: 11200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg/440px-Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg', bio: 'Founder of Amazon and Blue Origin. Former world\'s richest person who transformed global e-commerce.', tags: 'entrepreneur,amazon,blue-origin,billionaire' },
  { name: 'Kim Kardashian', category: 'Business & Tech', subcategory: 'Media/Business', nationality: 'American', birthYear: 1980, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.6, reviewCount: 19800, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Kim_Kardashian_2019_cropped.jpg/440px-Kim_Kardashian_2019_cropped.jpg', bio: 'Business mogul, reality TV star, and founder of SKIMS and KKW Beauty. Billionaire and criminal justice reform advocate.', tags: 'entrepreneur,reality-tv,skims,billionaire,fashion' },
  { name: 'Kylie Jenner', category: 'Business & Tech', subcategory: 'Media/Business', nationality: 'American', birthYear: 1997, meetPrice: 400000, virtualPrice: 120000, signingPrice: 80000, fanCardPrice: 49.99, rating: 4.5, reviewCount: 16700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Kylie_Jenner_2019_%28cropped%29.jpg/440px-Kylie_Jenner_2019_%28cropped%29.jpg', bio: 'Youngest self-made billionaire, founder of Kylie Cosmetics, and social media icon with 400M+ Instagram followers.', tags: 'entrepreneur,cosmetics,reality-tv,fashion' },

  // ── COMEDY ─────────────────────────────────────────────────────────────
  { name: 'Kevin Hart', category: 'Comedy', subcategory: 'Stand-up', nationality: 'American', birthYear: 1979, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 14500, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Kevin_Hart_2014_%28cropped%29.jpg/440px-Kevin_Hart_2014_%28cropped%29.jpg', bio: 'One of the highest-grossing comedians of all time. Stand-up legend, actor, and entrepreneur.', tags: 'comedy,stand-up,actor,entrepreneur' },
  { name: 'Dave Chappelle', category: 'Comedy', subcategory: 'Stand-up', nationality: 'American', birthYear: 1973, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.8, reviewCount: 12100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Dave_Chappelle_2019_by_Glenn_Francis.jpg/440px-Dave_Chappelle_2019_by_Glenn_Francis.jpg', bio: 'Grammy-winning comedian and creator of Chappelle\'s Show. One of the most celebrated stand-up comedians in history.', tags: 'comedy,stand-up,grammy,chappelles-show' },
  { name: 'Trevor Noah', category: 'Comedy', subcategory: 'Stand-up', nationality: 'South African', birthYear: 1984, meetPrice: 150000, virtualPrice: 48000, signingPrice: 32000, fanCardPrice: 34.99, rating: 4.7, reviewCount: 9800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Trevor_Noah_2019_by_Glenn_Francis.jpg/440px-Trevor_Noah_2019_by_Glenn_Francis.jpg', bio: 'Former Daily Show host and South African comedian. Known for Born a Crime memoir and global comedy tours.', tags: 'comedy,daily-show,south-african,author' },
  { name: 'Ellen DeGeneres', category: 'Comedy', subcategory: 'TV Host', nationality: 'American', birthYear: 1958, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.4, reviewCount: 9100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Ellen_DeGeneres_2011_Shankbone.JPG/440px-Ellen_DeGeneres_2011_Shankbone.JPG', bio: 'Emmy-winning comedian and talk show host who ran The Ellen DeGeneres Show for 19 seasons. LGBTQ+ pioneer.', tags: 'comedy,tv-host,emmy,lgbtq' },

  // ── FASHION & MODELING ──────────────────────────────────────────────────
  { name: 'Kendall Jenner', category: 'Fashion', subcategory: 'Modeling', nationality: 'American', birthYear: 1995, meetPrice: 350000, virtualPrice: 110000, signingPrice: 72000, fanCardPrice: 49.99, rating: 4.7, reviewCount: 14200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Kendall_Jenner_2019.jpg/440px-Kendall_Jenner_2019.jpg', bio: 'World\'s highest-paid supermodel. Walked for Chanel, Versace, and Victoria\'s Secret. Founder of 818 Tequila.', tags: 'model,fashion,818-tequila,entrepreneur' },
  { name: 'Bella Hadid', category: 'Fashion', subcategory: 'Modeling', nationality: 'American-Palestinian', birthYear: 1996, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.7, reviewCount: 10900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Bella_Hadid_2018_%28cropped%29.jpg/440px-Bella_Hadid_2018_%28cropped%29.jpg', bio: 'Supermodel who has walked for major fashion houses worldwide. Named Model of the Decade by Models.com.', tags: 'model,fashion,vogue,runway' },
  { name: 'Gigi Hadid', category: 'Fashion', subcategory: 'Modeling', nationality: 'American-Palestinian', birthYear: 1995, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.7, reviewCount: 10700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Gigi_Hadid_2018_%28cropped%29.jpg/440px-Gigi_Hadid_2018_%28cropped%29.jpg', bio: 'One of Forbes\' top-earning models. Global brand ambassador for Maybelline, Tommy Hilfiger, and Versace.', tags: 'model,fashion,maybelline,tommy-hilfiger' },
  { name: 'Naomi Campbell', category: 'Fashion', subcategory: 'Modeling', nationality: 'British', birthYear: 1970, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 8900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Naomi_Campbell_2019_%28cropped%29.jpg/440px-Naomi_Campbell_2019_%28cropped%29.jpg', bio: 'Legendary supermodel and the first Black woman on covers of Time, Vogue Paris, and French Elle.', tags: 'model,fashion,runway,british,pioneer' },

  // ── BOLLYWOOD ───────────────────────────────────────────────────────────
  { name: 'Shah Rukh Khan', category: 'Film & TV', subcategory: 'Bollywood', nationality: 'Indian', birthYear: 1965, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.9, reviewCount: 23100, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg/440px-Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg', bio: 'King Khan — the world\'s biggest movie star by box office. Star of Dilwale Dulhania Le Jayenge and Pathaan.', tags: 'bollywood,indian,king-khan,romantic' },
  { name: 'Priyanka Chopra', category: 'Film & TV', subcategory: 'Bollywood', nationality: 'Indian', birthYear: 1982, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 14700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Priyanka_Chopra_2019.jpg/440px-Priyanka_Chopra_2019.jpg', bio: 'Miss World 2000, Bollywood superstar, and Hollywood actress. Known for Quantico and The White Tiger.', tags: 'bollywood,hollywood,miss-world,actress' },
  { name: 'Deepika Padukone', category: 'Film & TV', subcategory: 'Bollywood', nationality: 'Indian', birthYear: 1986, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.8, reviewCount: 12900, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Deepika_Padukone_at_Cannes_2022_%28cropped%29.jpg/440px-Deepika_Padukone_at_Cannes_2022_%28cropped%29.jpg', bio: 'India\'s highest-paid actress. Known for Chennai Express, Padmaavat, and her mental health advocacy work.', tags: 'bollywood,actress,fashion,mental-health' },

  // ── K-POP ───────────────────────────────────────────────────────────────
  { name: 'BTS - Jin', category: 'Music', subcategory: 'K-Pop', nationality: 'South Korean', birthYear: 1992, meetPrice: 300000, virtualPrice: 95000, signingPrice: 60000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 28400, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/BTS_at_the_2019_Melon_Music_Awards_%28cropped_Jin%29.jpg/440px-BTS_at_the_2019_Melon_Music_Awards_%28cropped_Jin%29.jpg', bio: 'BTS member Jin (Kim Seokjin) — eldest member of the world\'s biggest K-pop group and solo artist.', tags: 'k-pop,bts,korean,worldwide-handsome' },
  { name: 'BLACKPINK - Lisa', category: 'Music', subcategory: 'K-Pop', nationality: 'Thai', birthYear: 1997, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 24600, featured: true, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/BLACKPINK_Lisa_at_the_2019_Korean_Music_Awards_%28cropped%29.jpg/440px-BLACKPINK_Lisa_at_the_2019_Korean_Music_Awards_%28cropped%29.jpg', bio: 'BLACKPINK rapper, dancer, and solo artist. Most followed K-pop artist on Instagram with 100M+ followers.', tags: 'k-pop,blackpink,thai,dance,model' },
  { name: 'BLACKPINK - Jennie', category: 'Music', subcategory: 'K-Pop', nationality: 'South Korean', birthYear: 1996, meetPrice: 250000, virtualPrice: 80000, signingPrice: 52000, fanCardPrice: 44.99, rating: 4.9, reviewCount: 22100, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/190420_BLACKPINK_JENNIE_Inkigayo_cropped.jpg/440px-190420_BLACKPINK_JENNIE_Inkigayo_cropped.jpg', bio: 'BLACKPINK member and Chanel ambassador. Solo artist known for SOLO and The Idol. Human Chanel.', tags: 'k-pop,blackpink,korean,chanel,actress' },
  { name: 'PSY', category: 'Music', subcategory: 'K-Pop', nationality: 'South Korean', birthYear: 1977, meetPrice: 150000, virtualPrice: 48000, signingPrice: 32000, fanCardPrice: 34.99, rating: 4.7, reviewCount: 9800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/PSY_at_KCON_2012_%28cropped%29.jpg/440px-PSY_at_KCON_2012_%28cropped%29.jpg', bio: 'Creator of Gangnam Style — YouTube\'s first billion-view video. Ambassador of Korean music globally.', tags: 'k-pop,korean,gangnam-style,viral' },

  // ── ROYALS & PUBLIC FIGURES ─────────────────────────────────────────────
  { name: 'Prince Harry', category: 'Royalty & Public Figures', subcategory: 'Royalty', nationality: 'British', birthYear: 1984, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.6, reviewCount: 16200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Prince_Harry_2017_Invictus_Games.jpg/440px-Prince_Harry_2017_Invictus_Games.jpg', bio: 'Duke of Sussex and Invictus Games founder. Known for his candid memoir Spare and mental health advocacy.', tags: 'royalty,british,invictus,veteran' },
  { name: 'Meghan Markle', category: 'Royalty & Public Figures', subcategory: 'Royalty', nationality: 'American', birthYear: 1981, meetPrice: 500000, virtualPrice: 150000, signingPrice: 100000, fanCardPrice: 59.99, rating: 4.5, reviewCount: 15800, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Meghan_Markle_2018_%28cropped%29.jpg/440px-Meghan_Markle_2018_%28cropped%29.jpg', bio: 'Duchess of Sussex, former actress, and women\'s rights advocate. Co-founder of Archewell Foundation.', tags: 'royalty,actress,humanitarian,author' },

  // ── SCIENCE & ACADEMIA ──────────────────────────────────────────────────
  { name: 'Neil deGrasse Tyson', category: 'Science & Academia', subcategory: 'Astrophysics', nationality: 'American', birthYear: 1958, meetPrice: 100000, virtualPrice: 32000, signingPrice: 21000, fanCardPrice: 29.99, rating: 4.8, reviewCount: 8700, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Neil_deGrasse_Tyson_2017.jpg/440px-Neil_deGrasse_Tyson_2017.jpg', bio: 'Astrophysicist, author, and science communicator. Director of Hayden Planetarium and host of Cosmos.', tags: 'science,astrophysics,cosmos,author,podcast' },
  { name: 'Malala Yousafzai', category: 'Science & Academia', subcategory: 'Activism', nationality: 'Pakistani', birthYear: 1997, meetPrice: 200000, virtualPrice: 65000, signingPrice: 42000, fanCardPrice: 39.99, rating: 5.0, reviewCount: 11400, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Malala_Yousafzai_-_World_Economic_Forum_Annual_Meeting_2014.jpg/440px-Malala_Yousafzai_-_World_Economic_Forum_Annual_Meeting_2014.jpg', bio: 'Youngest Nobel Peace Prize laureate. Girls\' education activist who survived Taliban assassination attempt.', tags: 'activism,education,nobel,pakistan' },

  // ── GAMING ─────────────────────────────────────────────────────────────
  { name: 'Ninja (Tyler Blevins)', category: 'Gaming', subcategory: 'Streaming', nationality: 'American', birthYear: 1991, meetPrice: 100000, virtualPrice: 32000, signingPrice: 21000, fanCardPrice: 24.99, rating: 4.7, reviewCount: 11200, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Ninja_2018_%28cropped%29.jpg/440px-Ninja_2018_%28cropped%29.jpg', bio: 'Most subscribed gaming streamer on Twitch. Known for Fortnite gameplay and mainstream gaming culture crossover.', tags: 'gaming,twitch,fortnite,streamer' },
  { name: 'Pokimane', category: 'Gaming', subcategory: 'Streaming', nationality: 'Moroccan-Canadian', birthYear: 1996, meetPrice: 75000, virtualPrice: 24000, signingPrice: 16000, fanCardPrice: 24.99, rating: 4.7, reviewCount: 9600, featured: false, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Pokimane_2022_%28cropped%29.jpg/440px-Pokimane_2022_%28cropped%29.jpg', bio: 'Most followed female Twitch streamer and co-founder of Offline TV. Gaming and entertainment personality.', tags: 'gaming,twitch,female-streamer,offline-tv' },
]

async function main() {
  console.log('🌟 Seeding StarConnect Pro database...')

  // Create admin user
  const adminPassword = await hash('Admin@StarConnect2024!', 12)
  const admin = await prisma.user.upsert({
    where: { email: 'management.team@mail.com' },
    update: {},
    create: {
      name: 'StarConnect Admin',
      email: 'management.team@mail.com',
      password: adminPassword,
      role: 'admin',
      image: 'https://ui-avatars.com/api/?name=Admin&background=f59e0b&color=fff&size=200',
    },
  })
  console.log(`✅ Admin user created: ${admin.email}`)

  // Create demo fan
  const fanPassword = await hash('Fan@Demo2024!', 12)
  await prisma.user.upsert({
    where: { email: 'demo@starconnect.pro' },
    update: {},
    create: {
      name: 'Demo Fan',
      email: 'demo@starconnect.pro',
      password: fanPassword,
      role: 'fan',
      image: 'https://ui-avatars.com/api/?name=Demo+Fan&background=7c3aed&color=fff&size=200',
    },
  })

  // Seed celebrities
  let created = 0
  for (const cel of celebrities) {
    const slug = slugify(cel.name)
    await prisma.celebrity.upsert({
      where: { slug },
      update: {},
      create: {
        name: cel.name,
        slug,
        category: cel.category,
        subcategory: cel.subcategory || null,
        bio: cel.bio,
        longBio: cel.bio + ' Their unique journey to the top has inspired millions of fans worldwide. Meet them in person for an unforgettable experience that you will treasure for a lifetime.',
        nationality: cel.nationality || null,
        birthYear: cel.birthYear || null,
        imageUrl: cel.imageUrl,
        meetPrice: cel.meetPrice,
        virtualPrice: cel.virtualPrice || cel.meetPrice * 0.3,
        signingPrice: cel.signingPrice || cel.meetPrice * 0.2,
        fanCardPrice: cel.fanCardPrice || 29.99,
        rating: cel.rating || 4.5,
        reviewCount: cel.reviewCount || rand(100, 5000),
        verified: true,
        featured: cel.featured || false,
        available: true,
        tags: cel.tags || '',
        instagram: cel.instagram || null,
        twitter: cel.twitter || null,
        totalBookings: rand(10, 500),
      },
    })
    created++
  }

  console.log(`✅ Seeded ${created} celebrities`)
  console.log('\n🎉 Database seeded successfully!')
  console.log('\n📋 Admin Credentials:')
  console.log('   Email: management.team@mail.com')
  console.log('   Password: Admin@StarConnect2024!')
  console.log('\n👤 Demo Fan Credentials:')
  console.log('   Email: demo@starconnect.pro')
  console.log('   Password: Fan@Demo2024!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
